#!/bin/bash

echo "========================================="
echo "Railway Setup Script untuk Bantu Tugas"
echo "========================================="
echo ""

echo "INFO: Setup Railway tanpa CLI"
echo ""
echo "LANGKAH-LANGKAH:"
echo ""
echo "1. Buka: https://railway.app"
echo "2. Login dengan GitHub"
echo "3. Klik project 'tranquil-enjoyment'"
echo ""
echo "========================================="
echo "STEP 1: Tambah MySQL Database"
echo "========================================="
echo ""
echo "Di Railway Dashboard:"
echo "  • Klik '+ Create' (sidebar kiri)"
echo "  • Pilih 'MySQL'"
echo "  • Tunggu database dibuat"
echo ""
echo "Status: Tunggu mysql service muncul"
echo ""

echo "========================================="
echo "STEP 2: Setup Environment Variables"
echo "========================================="
echo ""
echo "Klik service 'web', kemudian Tab 'Variables'"
echo "Tambahkan 13 variables berikut:"
echo ""
echo "1.  APP_KEY = base64:EC6MwBEixLVgQeJje4mEBkcp7GHIaHTitmYpIEGtQ4I="
echo "2.  APP_ENV = production"
echo "3.  APP_DEBUG = false"
echo "4.  CACHE_DRIVER = file"
echo "5.  SESSION_DRIVER = file"
echo "6.  QUEUE_CONNECTION = sync"
echo "7.  LOG_CHANNEL = stack"
echo "8.  DB_CONNECTION = mysql"
echo "9.  DB_HOST = \${MYSQL_HOST}"
echo "10. DB_PORT = \${MYSQL_PORT}"
echo "11. DB_DATABASE = \${MYSQL_DB}"
echo "12. DB_USERNAME = \${MYSQL_USER}"
echo "13. DB_PASSWORD = \${MYSQL_PASSWORD}"
echo ""

echo "========================================="
echo "STEP 3: Redeploy"
echo "========================================="
echo ""
echo "• Klik 'Redeploy' button"
echo "• Tunggu status 'Completed'"
echo ""

echo "========================================="
echo "STEP 4: Run Migrations"
echo "========================================="
echo ""
echo "Option A: Via Railway Logs"
echo "  • Click service 'web'"
echo "  • Tab 'Logs'"
echo "  • Input: php artisan migrate:fresh --seed"
echo ""
echo "Option B: Via PowerShell (Local)"
echo "  npx railway run php artisan migrate:fresh --seed"
echo ""

echo "========================================="
echo "STEP 5: Get Public URL"
echo "========================================="
echo ""
echo "• Klik service 'web'"
echo "• Lihat 'Public URL'"
echo "• Format: https://xxxx-xxxx.railway.app"
echo ""

echo "========================================="
echo "✅ DONE! Website siap di akses"
echo "========================================="
echo ""
